### ISSUE TITLE
How can I get ids with special characters in them?

### ISSUE THREAD

**Issue by edwardloveall** [kostya/myhtml#13]
I have an html document like this:

```html
<html>
<body>
  <div id="greeting()"></div>
</body>
</html>
```

As far as I can tell, I am unable to retrieve that `div` by `id` because of the parenthesis:

```crystal
require "myhtml"

doc = Myhtml::Parser.new(html)
doc.css("#greeting()") # empty
```

Am I missing anything? Or is this a bug in https://github.com/lexborisov/myhtml?

**Comment by kostya** [comment]
i don't know, you need to find how it works in css specification, myhtml fully support it. at least you can
```crystal
doc.nodes(:div).select { |node| node.attribute_by("id") == "greeting()" }.each { |node| ... }
```

**Comment by edwardloveall** [comment]
Thanks @kostya. Your suggestion did work. I'd like to dig into this a little bit more, and I'll try to get to it before the end of the week if that's okay.

**Comment by kostya** [comment]
this works: `doc.css(%q<[id="greeting()"]>)`, (), [] css reserved symbols.
