### ISSUE TITLE
Less to type?

### ISSUE THREAD

**Issue by proyb6** [kostya/myhtml#14]
In the PR and create example, I find it’s a little tedious to use (...) and node all the time.

div = tree.create_node(:div)
div.attribute_add("class", "red")
body.append_child(div)

Can be 

div = tree.create_div
div.attribute_add "class", "red"
body.append_child div

What do you think?

**Comment by kostya** [comment]
with `create_div` need to create method for each tag, not nice idea for me.
use '()' or not also just user style choice.
I think curent dsl is ok, because create html, not the main goal for this project.
for nice dsl you can use https://github.com/crystal-lang/html_builder or something else.
