### ISSUE TITLE
Parsing incomplete fragments

### ISSUE THREAD

**Issue by jgillich** [kostya/myhtml#17]
Example:
```crystal
html = <<-HTML
  <tr><td>Hello</td></tr>
  <tr><td>123</td><td>other</td></tr>
  <tr><td>foo</td><td>columns</td></tr>
  <tr><td>bar</td><td>are</td></tr>
  <tr><td>xyz</td><td>ignored</td></tr>
HTML

myhtml = Myhtml::Parser.new(html)
puts myhtml.css("tr td").map(&.to_html).to_a
# => []
```

Is this possible somehow? It only works once I wrap the HTML in `<table>`.

**Comment by kostya** [comment]
there is some fragment parsing methods in api: https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L545, need to learn how  to use it.

**Comment by kostya** [comment]
btw what the usage of this? why not add wrap with html all of this?

**Comment by jgillich** [comment]
I'm designing an API where this could come in handy. Thanks for your help, I will look into this and possibly send a PR your way.

**Comment by jgillich** [comment]
I didn't end up actually needing this and I guess nobody else does either, so I'm going to close this.

**Comment by kostya** [comment]
i tried it, but seems fragment method not work as expected.
