### ISSUE TITLE
Looking for a "inner_html" equivalent

### ISSUE THREAD

**Issue by captn3m0** [kostya/myhtml#19]
While there is `inner_text`, and `to_html`, neither of them achieves what I'm looking for: combined HTML for everything inside the node. 

```html
<div>
<a href="#">Link</a>
<p>Read this</p>
</div>
```

I want to get `<a href="#">Link</a><p>Read this</p>` as the complete inner_html of the node. I couldn't find a straight-forward way of doing this.

**Comment by kostya** [comment]
may be i will add this method to lib:
```crystal
require "myhtml"

page = <<-PAGE
<div>
<a href="#">Link</a>
<p>Read this</p>
</div>
PAGE

struct Myhtml::Node
  def inner_html
    String.build { |buf| children.each &.to_html(buf) }
  end
end

m = Myhtml::Parser.new(page)
puts m.nodes(:div).first.inner_html
```

**Comment by Dan-Do** [comment]
Can we have `node.inner_html = "<a href="#">Link</a><p>Read this</p>"`?

**Comment by kostya** [comment]
seems myhtml have no such api, but lexbor have: https://github.com/kostya/lexbor/blob/7dd06e44b1bddcd2f3f7d90a8b89568eb5c0a4aa/src/lexbor/node/tree_mutation.cr#L87
