### ISSUE TITLE
Unable to parse <template> tag

### ISSUE THREAD

**Issue by jwoertink** [kostya/myhtml#21]
When I try to parse the [template](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) tag, it just returns `nil`.

```crystal
html = Myhtml::Parser.new("<template>test</template>")
body = html.body!

puts body.children.inspect

#=> Myhtml::Iterator::Children(@start_node=Myhtml::Node(:body), @current_node=nil)
```

The strange thing is that I can make up random tags like `<jeremy>` and it parses those fine.

```crystal
html = Myhtml::Parser.new("<jeremy>test</jeremy>")
body = html.body!

puts body.children.inspect
#=> Myhtml::Iterator::Children(@start_node=Myhtml::Node(:body), @current_node=Myhtml::Node(:last_entry))
```

**Comment by kostya** [comment]
because it parsed to head:

```crystal
def walk(node, level = 0)
  puts "#{" " * level * 2}#{node.inspect}"
  node.children.each { |child| walk(child, level + 1) }
end

html = Myhtml::Parser.new("<template>test</template>")
walk(html.root!)
```

```
Myhtml::Node(:html)
  Myhtml::Node(:head)
    Myhtml::Node(:template)
      Myhtml::Node(:_text, "test")
  Myhtml::Node(:body)
```

**Comment by jwoertink** [comment]
Is there a way to tell if the input has a body tag? Right now the `html.body` method always returns a body.

```crystal
html = Myhtml::Parser.new("<template>test</template>")
body = html.body

puts body.inspect
#=> Myhtml::Node(:body)


html = Myhtml::Parser.new("<body><template>test</template></body>")
body = html.body

puts body.inspect
#=> Myhtml::Node(:body)
```

Even if I walk the tree, I can still get a body even if one isn't passed.

```crystal
html = Myhtml::Parser.new("<template>test</template>")

html.root!.walk_tree do |node, level|
  if node.tag_name == "body"
    # This is still printed out
    puts "has body"
  end
end
```

Just for a little background context on what I'm doing here, I'm working on this tool: https://luckyframework.org/convert-html-to-lucky. So I have no clue what the user will enter. It could be a snippet, or an entire document. I'm not able to blindly wrap the input in a `<body>` because the user might paste in a `<body>` already. We do this [here](https://github.com/luckyframework/website/blob/master/vendor/html2lucky/converter.cr#L11-L16).
