### ISSUE TITLE
Myhtml::Iterator::Collection#empty? returns different value when calling more than one times.

### ISSUE THREAD

**Issue by Kanezoh** [kostya/myhtml#27]
I found that `Myhtml::Iterator::Collection#empty?` doesn't return same value when calling more than one times.  I don't know why this happens, but I think it is not an expected behavior.

Here is a short example. Are there any mistakes in my code?

~~~
require "myhtml"

html = <<-HTML
<html>
<meta>
<head>
  <title>page title</title>
</head>
<body></body>
</html>
BODY
HTML

myhtml = Myhtml::Parser.new(html)
node = myhtml.css("title")
p node.size # => 1
p node.empty? # => true
p node.size # => 1
p node.empty? # => false
p node.size # => 1
p node.empty? # => false
~~~

btw, thank you for this library. myhtml is very helpful.

**Comment by kostya** [comment]
Collection is not array, it is iterator. This is how iterator work in Crystal, So calling `empty?` do iterate on collection. If you want it behave like array, you should call `to_a`. 

You can also use `rewind`.
```crystal
p node.size # => 1
p node.empty? # => false
node.rewind
p node.size # => 1
p node.empty? # => false
node.rewind
p node.size # => 1
p node.empty? # => false
```

**Comment by kostya** [comment]
Actually change it to indexable, as i think is much better, and now this work (in master).

**Comment by Kanezoh** [comment]
Sorry, I didn't understand the behavior of Iterator.
And thank you for change node collection to indexable. This change makes myhtml more useful.
