### ISSUE TITLE
cant cd to src/ext

### ISSUE THREAD

**Issue by yorci** [kostya/myhtml#3]
hi, im newbie in crystal language, i try to use your package but when i run crystal deps its return that error 

> crystal deps
> Updating https://github.com/kemalcr/kemal.git
> Updating https://github.com/luislavena/radix.git
> Updating https://github.com/jeromegn/kilt.git
> Updating https://github.com/RX14/multipart.cr.git
> Updating https://github.com/kostya/myhtml.git
> Updating https://github.com/kostya/modest.git
> Using kemal (ac8ec0a07b5929dc1656006a135e08a2a2732f5e)
> Using radix (0.3.5)
> Using kilt (0.3.3)
> Using multipart (0.1.1)
> Installing myhtml (master)
> Postinstall cd src/ext && make package
> **Failed cd src/ext && make package:**
> **/bin/sh: 1: cd: can't cd to src/ext**

**Comment by kostya** [comment]
crystal version? should be last

**Comment by yorci** [comment]
> cat /proc/version
> Linux version 4.4.0-53-generic (buildd@lcy01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
> crystal -v
> Crystal 0.19.4 [7f82f79] (2016-10-07) 

@kostya

**Comment by kostya** [comment]
should be >= 0.20
